yc climacons-font.css -o climacons-font.min.css 
yc dripicons.css -o dripicons.min.css 
yc iconvault.css -o iconvault.min.css 
yc pe-icon-set-weather.css -o pe-icon-set-weather.min.css 
yc weather-icons.css -o weather-icons.min.css 
yc weather-icons-wind.css -o weather-icons-wind.min.css
yc wpcloudy-admin.css -o wpcloudy-admin.min.css 
yc wpcloudy-anim.css -o wpcloudy-anim.min.css 
yc wpcloudy.css -o wpcloudy.min.css 
yc wpcloudy-map.css -o wpcloudy-map.min.css 
